[package]
name = "mdfr"
version = "0.1.0"
authors = ["«ratal» <«ratal@rseek_bufread ! atal.org»>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
#xml-rs = "0.8"
byteorder = "1.4"
#bincode = "1.3"
#nom = "6"
#rayon = "1.5"
encoding = "0.2"
chrono = "0.4.19"
roxmltree = "0.14"
#structure = "0.1"
#packed_struct  = "0.5"
#byteordered = "0.5"
#structview = "1.1"
#seek_bufread = "1.2"
binread = "2.1"
criterion = "0.3"
tokio = "1.5"
#numpy = "0.13"
#ndarray = "0.15.1"

#[lib]
#name = "mdfr"
#crate-type = ["rlib", "cdylib"]

#[dependencies.pyo3]
#version = "0.13.2"
#features = ["extension-module"]

[[bench]]
name = "mdf_benchmark"
harness = false