[package]
name = "mdfr"
version = "0.1.0"
authors = ["«ratal» <«ratal@ratal.org»>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2" # for input arguments 
byteorder = "1.4"
rayon =  "1.5" # for general purpose parallel computations
dashmap = {version = "4", features = ["rayon"]} # for parallel hashmap computations
encoding = "0.2"
chrono = "0.4.19" # for time conversion
roxmltree = "0.14" # for xml parsing
binread = "2.1" # for easy reading of struct
criterion = "0.3" # for benchmark
num = "0.4" # for complex numbers
half = "1" # for f16 handling
encoding_rs = "0.8" # for endian management
#tokio = "1.5"
#numpy = "0.13"
ndarray = {version = "0.15", features = ["rayon"]} # for nd arrays
rustfilt = "0.2"
yazi = "0.1"
transpose = "0.2"

#[lib]
#name = "mdfr"
#crate-type = ["rlib", "cdylib"]

#[dependencies.pyo3]
#version = "0.13.2"
#features = ["extension-module"]

[[bench]]
name = "mdf_benchmark"
harness = false

[profile.release]
opt-level = 3
debug = 2
lot = true

[profile.bench]
debug = false
opt-level = 3

[rust]
debuginfo-level = 2
