[package]
name = "mdfr"
version = "0.1.0"
authors = ["«ratal» <«ratal@ratal.org»>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
byteorder = "1.4"
rayon =  "1.5"
dashmap = {version="4", features = ["rayon"]}
encoding = "0.2"
chrono = "0.4.19"
roxmltree = "0.14"
binread = "2.1"
criterion = "0.3"
#tokio = "1.5"
#numpy = "0.13"
ndarray = "0.15"

#[lib]
#name = "mdfr"
#crate-type = ["rlib", "cdylib"]

#[dependencies.pyo3]
#version = "0.13.2"
#features = ["extension-module"]

[[bench]]
name = "mdf_benchmark"
harness = false

[profile.release]
debug = true
lot = true

[profile.bench]
debug = true

[rust]
debuginfo-level = 1