[build-system]
requires = ["maturin>=1.8"]
build-backend = "maturin"

[project]
name = "mdfr"
version = "0.6.3"
dependencies = [
  "numpy>=1.23","polars>=0.13","matplotlib>=3.5"
]
requires-python = ">=3.8"
license = {file = "LICENSE"}