name: Create macOs universal2/aarch64-apple-darwin python release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Setup universal2 targets for Rust
        run: |
          rustup target add aarch64-apple-darwin
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Prepare maturin publish
        shell: bash
        run: |
          rustup override set nightly
      - name: maturin publish
        uses: messense/maturin-action@v1
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        with:
          maturin-version: latest
          command: publish
          args: --target aarch64-apple-darwin --skip-existing --no-sdist -o wheels -i python -u __token__