name: Create Python release manylinux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_manylinux:
    name: Create Release manylinux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          default: true
      - name: Run tests
        run: cargo test tests::basic_test --verbose
      - name: build x64_64
        uses: messense/maturin-action@v1
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_PASS }}
          RUSTFLAGS: '-C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma'
        with:
          rust-toolchain: nightly
          maturin-version: latest
          command: build
          args: --no-sdist --universal2 --out dist -o wheels -i python
      - name: build aarch64
        uses: messense/maturin-action@v1
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_PASS }}
        with:
          rust-toolchain: nightly
          target: aarch64-unknown-linux-gnu
          maturin-version: latest
          command: build
          args: --no-sdist --universal2 --out dist -o wheels -i python
      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: dist
