name: Create Python release manylinux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_manylinux:
    name: Create Release manylinux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10' , "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: build x64_64
        uses: messense/maturin-action@v1
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          RUSTFLAGS: '-C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma'
        with:
          rust-toolchain: nightly
          maturin-version: latest
          manylinux: auto
          command: publish
          args: --skip-existing --no-sdist -i python3.11 -o wheels -u __token__
      - name: build aarch64
        uses: messense/maturin-action@v1
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        with:
          rust-toolchain: nightly
          target: aarch64-unknown-linux-gnu
          maturin-version: latest
          command: publish
          args: --skip-existing --no-sdist -o wheels -i python3.11 -u __token__
